version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    ports:
      - 80:80

  php:
    build:
      context: .
      dockerfile: './docker/php/Dockerfile'
    volumes:
      - './src:/var/www/html'